### ISSUE TITLE
rc2 library dependency should be removed

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zgrab#103]
As discussed in #102, the dependency on https://github.com/dadrian/rc2 should be removed.

**Comment by dadrian** [comment]
I forked the rc2 library under the ZMap organization, see https://github.com/zmap/rc2. We should point the dependency at that repository instead of mine.

**Comment by zakird** [comment]
I'm still at a total loss why we have a repository to contain a single file.

**Comment by dadrian** [comment]
@zakird because it's a crypto cipher I took from a fork of a repository by @tqbf, was standalone implemented, and we may eventually need to merge in upstream changes.

**Comment by zakird** [comment]
We've already forked a lot. Having another file with a cipher in it isn't going to cause major problems.

**Comment by dadrian** [comment]
Why should we do manual forking when we don't have to, given that running `go get` automatically solves this for us anyway?

**Comment by zakird** [comment]
what manual forking is there? Aren't we talking copying a file?

**Comment by dadrian** [comment]
> @zakird because it's a crypto cipher I took from a fork of a repository by @tqbf, was standalone implemented, and we may eventually need to merge in upstream changes.

**Comment by zakird** [comment]
I don't follow what you're saying. I understand that this came from another location. However, this doesn't affect what the correct thing to do going forward. It seems fairly unlikely to me that there are going to be changes to the RC2 algorithm given that this is an algorithm deprecated decades ago. If you are trying to communicate something else, it would be helpful to all of us if you could explain your idea directly to us.

**Comment by dadrian** [comment]
I'm saying that given that Golang has built-in support for *exactly* this situation, I don't understand why we should copy the file into our repo instead of just using the built-in ability to fetch remote dependencies. When we leave it in it's own repository, it's easier to keep track of where it came from, compared to copying and pasting the implementation into the ZGrab repo. Additionally, we don't have to modify the package name header at the top of the file. This adds *zero* complexity when developing ZGrab, because the code is automatically fetched when you run `go get`. I also view this as nicer to the original developer, because it's easier to see who forked and is using your repository vs who copy/pasted d your code into theirs.

I recognize wanting to fork it and keep it under the ZMap organization so that we remain in control of when any (unlikely) future changes are merged, but I see no reason to give up the (even marginal) tracking and merge benefits we get from forking the repo through Github, given that the developer effort required to use the dependency is exactly the same as the effort required were it copy/pasted in.

**Comment by zakird** [comment]
Alright, for now, let's just move it to the ZMap organization. I don't know if I agree, but this solves the major concern for the time being.

**Comment by tqbf** [comment]
Is there some way I can, like, donate that RC2 code to ZMap in perpetuity so every time someone else on the Internet decides they need RC2 for something they can bug you guys about it? :)

I don’t even remember why I wrote that code.

-- 
Thomas Ptacek


On January 3, 2016 at 8:59:58 PM, Zakir Durumeric (notifications@github.com) wrote:

Alright, for now, let's just move it to the ZMap organization. I don't know if I agree, but this solves the major concern for the time being.
