### ISSUE TITLE
--tls should default to port 443 or require a port argument

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zgrab#210]
Currently `zgrab --tls` defaults to port 80, which seems worse than either requiring a port or defaulting to port 443.

**Comment by umbernhard** [comment]
Turns out this is tricky. In order to default to 443 for TLS but still allow people to force port 80, we need to roll our own golang flag (see [here](https://stackoverflow.com/questions/35809252/check-if-flag-was-provided-in-go)).

Then we have to figure out how to get a default value into that. Or we could just assume that if people want to use TLS they're never going to force port 80. If we do that, it's really easy.

**Comment by zakird** [comment]
ZGrab2, which is superseding this project has default ports for modules. Closing.
