### ISSUE TITLE
implement --version

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#23]

**Comment by Rolinh** [comment]
I know this issue a bit old but if you guys could use semantic versioning or something this would be great.
As soon as you use versioning, I think it would be good to include the zgrab version in the base grab json objects so that we know how we need to deserialize it.

**Comment by dadrian** [comment]
Including the version/commit hash in the JSON output is a good idea. We should add it to the metadata output.

However, I'm not sure if we should bother with semantic versioning yet. We're still trying to figure out where exactly zgrab is going and what we want it to look like. If we did switch to semantic versioning, at this point we'd still be version 0.x.y. Semantic versioning provides no guarantees for software with 0 as the major rev, so we'd essentially still be in the same situation we are now. If you're experiencing stability issues, our current recommendation is to fork the repository and pull in changes from upstream as needed.

**Comment by Rolinh** [comment]
Well, semantic versioning was just a proposition. The only thing I really care about is to be able to know when there are changes in the code that modify the JSON output so that I known how I am suppose to deserialize it. Sometimes users want to read a JSON file that was produced several month ago, for comparison with current data or whatever, so if the format change, users should be able to know how to deserialize it still.
