### ISSUE TITLE
--lookup-domain doesn't work

### ISSUE THREAD

**Issue by bonkc** [zmap/zgrab#298]
With the command

zgrab --input-file=domains.all --lookup-domain --port 80 --output-file=domains.all.80.callback

when domains.all is a file with one domain per line, doesn't work. The error is produced:

Nov 18 21:59:33.323 [ERROR] banner-grab: Could not connect to <redact> remote host <nil>: dial tcp: lookup <nil>: no such host

Whats the proper usage of --lookup-domain ? --help says input contains domains only.

**Comment by ajholland** [comment]
If you're trying to grab on http you'll need to use the `--http=/` flag for grabbing on a default endpoint.

The confusing command line arguments will be resolved in the next version of zgrab.

**Comment by bonkc** [comment]
What if the parameter --data is used? --http seems to override the custom HTTP payload in --data.

**Comment by nmalcolm** [comment]
Can confirm the same behavior as @bonkc.

**Comment by amcdonald714** [comment]
I also observe this problem when testing domains without A records.

For example:
echo "mozilla.net" | zgrab --port 80 --http="/" -http-max-redirects 10 -lookup-domain
results in "error":"Get http://mozilla.net/: dial tcp: lookup mozilla.net: no such host"

But prepending "www." works:
echo "www.mozilla.net" | zgrab --port 80 --http="/" -http-max-redirects 10 -lookup-domain

**Comment by zakird** [comment]
@amcdonald714 `mozilla.net` does not have an A record. This isn't a problem with ZGrab.

**Comment by zakird** [comment]
@amcdonald714, @cdzombak just pointed out to me that I missed part of your message, and that you acknowledge that mozilla.net doesn't have an A record. Sorry about that. Given that mozilla.net doesn't have an A record, I don't think I understand though what you're expecting to happen. Can you elaborate?

**Comment by amcdonald714** [comment]
Right, sorry, I didn't really explain what I was getting at. Browsers, for example, will correct for a missing "www" if the domain doesn't resolve---so mozilla.net will load in a browser as www.mozilla.net. Is this something we would want zgrab to do as well?

Thinking about this more, it doesn't seem like it should be zgrab's job. But to give some context, I'm zgrabbing a set of ~4000 domains out of the Alexa top 1m, and almost 10% of them are not resolving because they don't have the "www." version configured in DNS. I think the frequency is an artifact of the domains I'm testing with, but regardless it's a more common occurrence than I expected.

**Comment by zakird** [comment]
I don't think think that this something that we want ZGrab to do
automatically at the framework level since HTTP is one of many modules that
ZGrab supports. That said, I'm opposed to a pull request that adds a flag
to do this in ZGrab 2.0.

I'll also note that this doesn't quite jive with my personal browser
experience. When I go to http://mozilla.net/ in Chrome, I receive the
following error:

This site can’t be reached.

*mozilla.net <http://mozilla.net>*’s server DNS address could not be found.

Zakir
